version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: acon3d:${ACON3D_VERSION:-latest}
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      ACON3D_HOST: 0.0.0.0
      ACON3D_DB_HOST: acon3d-db
      ACON3D_DB_PORT: 5432
      ACON3D_DB_USER: acon3d
      ACON3D_DB_PASS: acon3d
      ACON3D_DB_BASE: acon3d
    entrypoint: bash
